export const GET_ALBUM_REQUEST = "GET_ALBUM_REQUEST"
export const GET_ALBUM_SUCCESS = "GET_ALBUM_SUCCESS"
export const GET_ALBUM_FAILURE = "GET_ALBUM_FAILURE"

export const EDIT_ALBUM_REQUEST = "EDIT_ALBUM_REQUEST"
export const EDIT_ALBUM_SUCCESS = "EDIT_ALBUM_SUCCESS"
export const EDIT_ALBUM_FAILURE="EDIT_ALBUM_FAILURE"